# Generated by Django 4.2.2 on 2023-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postget', '0002_customer_food_order_tag_delete_room_food_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Pick up', 'Pick up'), ('Delivery', 'Delivery')], max_length=150, null=True),
        ),
    ]
