# Generated by Django 4.2.2 on 2023-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_of_room',
            field=models.CharField(max_length=100),
        ),
    ]
